### PR TITLE
add crypto_box_seal

### PR DESCRIPTION
**Pull request by plneple**

### CODE REVIEW

**Comment by nikgraf** [comment]
@plneple looks great! can you also add tests for it like these ones? https://github.com/serenity-kit/react-native-libsodium/blob/main/example/src/tests/crypto_box_easy_test.ts

**Comment by plneple** [comment]
@nikgraf
Disclaimer: I am not at all familiar with libsodium

It seems to me that the output from the `crypto_box_seal` function is dependent on the nonce generated inside of libsodium. [Documentation](https://libsodium.gitbook.io/doc/public-key_cryptography/sealed_boxes).
I believe, that means that I cannot write out the expected output statically, and calculating it might have it's own bugs.

**Comment by nikgraf** [comment]
@plneple totally, but the what would work as a test is creating the encryption and verifying it with a decryption. A test here is really important to make sure this works on all environments and this way we can dedect breaking changes with the e2e tests

**Comment by plneple** [comment]
@nikgraf I have added `crypto_box_seal_open` and tested `crypto_box_seal` using it, as you suggested.

**Review by nikgraf — APPROVED** [review]
looks great! thanks you @plneple 🙌

**Comment by nikgraf** [comment]
@plneple just released 1.3.0 which includes your additions 👍

**Pull request merged**
